<a href="https://colab.research.google.com/github/Anirban095/Hackerrank-Practices/blob/main/Python_Intermediate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Collection Counter

In [ ]:
from collections import Counter

In [ ]:
myList = [1,1,2,3,4,5,3,2,3,4,2,1,2,3]

In [ ]:
print(Counter(myList))

Counter({2: 4, 3: 4, 1: 3, 4: 2, 5: 1})


In [ ]:
print(Counter(myList).items())

dict_items([(1, 3), (2, 4), (3, 4), (4, 2), (5, 1)])


In [ ]:
numShoes = int(input())
shoes = Counter(map(int, input().split()))
numCust = int(input())

income = 0

for i in range(numCust):
  size, price = map(int, input().split())
  if(shoes[size]):
    income += price
    shoes[size] -= 1
print(income)

10
2 3 4 5 6 8 7 6 5 18
3
2 100
2 500
5 25
125


# Company Logo

In [ ]:
logo_Counter = Counter(list(sorted('qwertyuiopasdfghjklzxcvbnm')))
logo_Counter

Counter({'a': 1,
         'b': 1,
         'c': 1,
         'd': 1,
         'e': 1,
         'f': 1,
         'g': 1,
         'h': 1,
         'i': 1,
         'j': 1,
         'k': 1,
         'l': 1,
         'm': 1,
         'n': 1,
         'o': 1,
         'p': 1,
         'q': 1,
         'r': 1,
         's': 1,
         't': 1,
         'u': 1,
         'v': 1,
         'w': 1,
         'x': 1,
         'y': 1,
         'z': 1})

In [ ]:
logo_Counter.keys()

dict_keys(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'])

In [ ]:
bruh = logo_Counter.most_common(3)
bruh

[('a', 1), ('b', 1), ('c', 1)]

In [ ]:
for i in range(3):
  print(f'{bruh[i][0]} {bruh[i][1]}')

a 1
b 1
c 1


In [ ]:
def GetCompanyLogo(name):
  myCounter = Counter(list(sorted(name)))
  nameLen = len(myCounter)
  top3 = myCounter.most_common(3)
  range_index = 3
  if(nameLen < 3):
    range_index = nameLen
  for i in range(range_index):
    print(f'{top3[i][0]} {top3[i][1]}')


In [ ]:
GetCompanyLogo('qwertyuiopasdfghjklzxcvbnm')

a 1
b 1
c 1


# Cartesian product


In [ ]:
list1 = list(input().split())
list2 = list(input().split())
print(list1)
print(list2)

1 2
3 4
['1', '2']
['3', '4']


In [ ]:
for i in list1:
  for j in list2:
    print(f'({i}, {j})', end=' ')

(1, 3) (1, 4) (2, 3) (2, 4) 

# The Minion Game

In [ ]:
s = input()

vowels = 'AEIOU'

kevsc = 0
stusc = 0
for i in range(len(s)):
    if s[i].lower() in vowels.lower():
        kevsc += (len(s)-i)
    else:
        stusc += (len(s)-i)

if kevsc > stusc:
    print(f'Kevin wins {kevsc}')
elif kevsc < stusc:
    print(f'Stuart wins {stusc}')
else:
    print('Draw')

banana
Stuart wins 12


In [ ]:
string = 'BANANA'

In [ ]:
for i in range(len(string)):
  if string[i] in vowels:
    print(f'Vowels: {len(string) - i}')
  else:
    print(f'Consonants: {len(string) - i}')

Consonants: 6
Vowels: 5
Consonants: 4
Vowels: 3
Consonants: 2
Vowels: 1


In [ ]:
vowels

'AEIOU'

# Sets

In [ ]:
tot_sets = int(input())

for i in range(tot_sets):
  len_setA = int(input())
  setA = list(input().split())
  len_setB = int(input())
  setB = list(input().split())
  print(isSubset(setA, setB))

#for i in range(tot_sets):
 # print(IsSubset(list_setA[i], list_setB[i]))

3
5
1 2 3 4 5
9
9 8 5 6 3 2 1 4 7
True
1
2
5
3 6 5 4 14
False
7
1 2 3 5 6 8 9
3
9 8 2
False


In [ ]:
def isSubset(setA, setB):
  isSubset = False
  for i in range(len(setA)):
    if setA[i] in setB:
      isSubset = True
    else:
      isSubset = False
      break
  return isSubset

In [ ]:
setA = list(input().split())
tot_checkSet = int(input())
isSuperSet = False
for i in range(tot_checkSet):
  checkSet = list(input().split())
  if(isSubset(checkSet, setA)):
    isSuperSet = True
  else:
    isSuperSet = False
    break
print(isSuperSet)


1 2 3 4 5 6 7 8 9 10 11 12 23 45 84 78
2
1 2 3 4 5
100 11 12
False


In [ ]:
True and False

False

# Math

In [ ]:
import cmath

In [ ]:
cmath.phase(complex(1,2))

1.1071487177940904

In [ ]:
abs(complex(1,2))

2.23606797749979

In [ ]:
abs(complex(1 + 2j))

2.23606797749979

In [ ]:
str(round(math.degrees(math.atan2(10,20)))) + '°'

'27°'

In [ ]:
x, y = map(int, input().split())
val = eval(input())
print(val == y)

1 3
x**3 + x**2 + x + 1
False


In [ ]:
eval(input())

print(2+10)
12


In [ ]:
a, myList = int(input()), input().split()
print(all([int(i) > 0 for i in myList]) and any([j == j[::-1] for j in myList]))

6
1 2 3 4 5 -9
False


In [ ]:
all([5 > 4 and 2==2])

True

In [ ]:
print(zip([1, 2, 3, 4], 'hack'))

# Numpy

In [ ]:
import numpy as np

In [ ]:
shape = list(map(int, input().split()))
print(np.zeros(shape, dtype=np.int))
print(np.ones(shape, dtype = np.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Depreca

In [ ]:
print(np.zeros([3, 3, 3]))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
myList = []
r, c = tuple(map(int, input().split()))
for i in range(r):
  myList.append(list(map(int, input().split())))
print(np.transpose(np.array(myList)))
print(np.array(myList).flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [ ]:
list1 = []
list2 = []
n, m, p = tuple(map(int, input().split()))
for i in range(n):
  list1.append(list(map(int, input().split())))
for i in range(m):
  list2.append(list(map(int, input().split())))
np_array1 = np.array(list1, dtype = int)
np_array2 = np.array(list2, dtype = int)
print(np.concatenate(np.array(list1), np.array(list2)))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4


In [ ]:
print(np.concatenate((np_array1, np_array2), axis = 0))

[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [ ]:
print(np.eye(3, 3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
n, m = tuple(map(int, input().split()))
print(np.eye(n, m))

3 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
np_array = list({1, 3, 5, 2, 2})

In [ ]:
np_array

[1, 2, 3, 5]

In [ ]:
np_array[:2]

[1, 2]

In [ ]:
np_array[2:]

[3, 5]

In [ ]:
for i in range(2,5):
  print(i)

2
3
4


In [ ]:
equalSum([1,3,5,2,2], 5 )

3


In [ ]:
equalSum(list(map(int, '4 42 27 16 28 3 4 5 9 3 31 5 5 29 10 18 35 35 33 19 41 23 8 32 9 5 8 18 35 13 6 7 6 10 11 13 37 2 25 7 28 43'.split())), 42)

0


In [ ]:
n, m = tuple(map(int, input().split()))
num_A = np.zeros((n,m), int)
num_B = np.zeros((n,m), int)
for i in range(n):
    num_A[i] = np.array(input().split(), int)

for i in range(n):
    num_B[i] = np.array(input().split(), int)

print(np.add(num_A, num_B))
print(np.subtract(num_A, num_B))
print(np.multiply(num_A, num_B))
print(np.floor_divide(num_A, num_B))
print(np.mod(num_A, num_B))
print(np.power(num_A, num_B))

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [ ]:
n, m = tuple(map(int, input().split()))
myList = []
for i in range(n):
  myList.append(tuple(map(int, input().split())))
print(np.prod(np.array(myList)))

2 2
1 2
3 2
12


In [ ]:
n, m = tuple(map(int, input().split()))
myList = []
for i in range(n):
    myList.append(tuple(map(int, input().split())))

print(np.mean(np.array(myList), axis =1))
print(np.var(np.array(myList), axis =0))
print(np.std(np.array(myList)))

2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.118033988749895


In [ ]:
print(round(np.std(np.array(myList)), 11))

1.11803398875


MATRIX Multiplication

In [ ]:
n = int(input())
    
A = np.array([input().split() for i in range(n)], int)
B = np.array([input().split() for i in range(n)], int)

print(np.dot(A, B))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [ ]:
A = np.array(input().split(), int)
B = np.array(input().split(), int)
print(np.inner(A,B))
print(np.outer(A,B))

1 2
3 4
11
[[3 4]
 [6 8]]


In [ ]:
 n = int(input())
myList = []

for i in range(n):
    myList.append(list(map(float, input().split())))

print(np.linalg.det(myList))

2
1.1 1.1
1.1 1.2
0.10999999999999982


# Exceptions

In [ ]:
n = int(input())
for i in range(n):
    try:
      a, b = tuple(map(str, input().split()))
      char = ''
      if(str.isnumeric(a)):
          char = b
      else:
          char = a
      print(int(int(a)/int(b)))
    except ZeroDivisionError as e:
        print('Error Code: integer division or modulo by zero')
    except ValueError as f:
        print(f"Error Code: invalid literal for int() with base 10: '{char}'")

3
# #
Error Code: invalid literal for int() with base 10: '#'
% $
Error Code: invalid literal for int() with base 10: '%'
2 1
2


In [ ]:
import re

def isvalidregex(regex):
    try: re.compile(regex)
    except re.error: return False
    return True

for i in range(int(input())):
    print(isvalidregex(input()))

3
.*\+
True
.*+
False
##$
True


# Lambda Function

In [ ]:
cube = lambda x: x**3

def fibonacci(n):
  if n<2:
    return [0]*n
  lst = [0, 1]
  for i in range(2, n):
    lst.append(lst[i-1] + lst[i-2])
  return lst

In [ ]:
list(map(cube, fibonacci(4)))

[0, 1, 1, 8]

Email Verification

In [ ]:
def fun(email):
  body_tail = email.split('@')
  if(len(body_tail) > 2):
    print('1')
    return False
  
  username, website, domain = (body_tail[0], body_tail[1].split('.')[0], body_tail[1].split('.')[1]) 
  if(len(domain) > 3):
    print('2')
    return False
  if(username.replace('-', '').replace('_', '').isalnum() == False):
    print('3')
    return False
  if(website.isalnum() == False):
    print('4')
    return False
  if(domain.isalpha() == False):
    print('5')
    return False
  return True
  
def filter_mail(emails):
  return list(filter(fun, emails))

In [ ]:
emails = ['lara@hackerrank.com', 'brian-23@hackerrank.com', 'britts_54@hackerrank.com']
#print(filter_mail(emails))
filtered_emails = filter_mail(emails)
filtered_emails.sort()
print(filtered_emails)

['brian-23@hackerrank.com', 'britts_54@hackerrank.com', 'lara@hackerrank.com']


In [ ]:
fun(emails[0])

True

In [ ]:
'-' in 'asda123-__#asdas@ada21da.com'

True

In [ ]:
filter_email('asda123-__asdas@ada21da.com')

In [ ]:
def fun(s):
    try: 
        body_tail = s.split('@')
        if(len(body_tail) is not 2):
            return False
        username, extension = (body_tail[0], body_tail[1])
        if(len(extension.split('.')) is not 2 ):
            return False
        website, domain = (extension.split('.')[0], extension.split('.')[1])
    
    except ValueError:
        return False
        
    if(len(body_tail) > 2):
        return False
      
    if(len(domain) > 3):
        return False
    if(username.replace('-', '').replace('_', '').isalnum() == False):
        return False
    if(website.isalnum() == False):
        return False
    if(domain.isalpha() == False):
        return False
    print(s)
    return True
    
    
def filter_mail(emails):
    return list(filter(fun, emails))

if __name__ == '__main__':
    n = int(input())
    emails = []
    for _ in range(n):
        emails.append(input())
    filtered_emails = filter_mail(emails)
    filtered_emails.sort()
    print(filtered_emails)

2
harsh@gmail
iota_98@hackerrank.com
iota_98@hackerrank.com
['iota_98@hackerrank.com']


In [ ]:
if __name__ == '__main__':
    n = int(input())
    emails = []
    for _ in range(n):
        emails.append(input())
    emails.sort()
    print(emails)

3
b
a
u
['a', 'b', 'u']


In [7]:
from fractions import Fraction
from functools import reduce
from fractions import gcd

if __name__ == '__main__':
    fracs = []
    for _ in range(int(input())):
        fracs.append(Fraction(*map(int, input().split())))
    n = reduce(lambda x, y: x*y, fracs)
    print(n.numerator, n.denominator)
    #result = product(fracs)
    #print(*result)

2
1 2
1 3
1 6


In [9]:
def product(fracs):
    #t = # complete this line with a reduce statement
    t = reduce(lambda x, y: x*y, fracs)
    return t.numerator, t.denominator

if __name__ == '__main__':
    fracs = []
    for _ in range(int(input())):
        fracs.append(Fraction(*map(int, input().split())))
    result = product(fracs)
    print(*result)

3
1 2
3 4
10 6
5 8


In [5]:
reduce(lambda x, y: x*y, [Fraction(1,2), Fraction(1,3)])

Fraction(1, 6)

# GFG Exams