<a href="https://colab.research.google.com/github/Anirban095/Hackerrank-Practices/blob/main/Python_Intermediate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Collection Counter

In [ ]:
from collections import Counter

In [ ]:
myList = [1,1,2,3,4,5,3,2,3,4,2,1,2,3]

In [ ]:
print(Counter(myList))

Counter({2: 4, 3: 4, 1: 3, 4: 2, 5: 1})


In [ ]:
print(Counter(myList).items())

dict_items([(1, 3), (2, 4), (3, 4), (4, 2), (5, 1)])


In [ ]:
numShoes = int(input())
shoes = Counter(map(int, input().split()))
numCust = int(input())

income = 0

for i in range(numCust):
  size, price = map(int, input().split())
  if(shoes[size]):
    income += price
    shoes[size] -= 1
print(income)

10
2 3 4 5 6 8 7 6 5 18
3
2 100
2 500
5 25
125


# Company Logo

In [ ]:
logo_Counter = Counter(list(sorted('qwertyuiopasdfghjklzxcvbnm')))
logo_Counter

Counter({'a': 1,
         'b': 1,
         'c': 1,
         'd': 1,
         'e': 1,
         'f': 1,
         'g': 1,
         'h': 1,
         'i': 1,
         'j': 1,
         'k': 1,
         'l': 1,
         'm': 1,
         'n': 1,
         'o': 1,
         'p': 1,
         'q': 1,
         'r': 1,
         's': 1,
         't': 1,
         'u': 1,
         'v': 1,
         'w': 1,
         'x': 1,
         'y': 1,
         'z': 1})

In [ ]:
logo_Counter.keys()

dict_keys(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'])

In [ ]:
bruh = logo_Counter.most_common(3)
bruh

[('a', 1), ('b', 1), ('c', 1)]

In [ ]:
for i in range(3):
  print(f'{bruh[i][0]} {bruh[i][1]}')

a 1
b 1
c 1


In [ ]:
def GetCompanyLogo(name):
  myCounter = Counter(list(sorted(name)))
  nameLen = len(myCounter)
  top3 = myCounter.most_common(3)
  range_index = 3
  if(nameLen < 3):
    range_index = nameLen
  for i in range(range_index):
    print(f'{top3[i][0]} {top3[i][1]}')


In [ ]:
GetCompanyLogo('qwertyuiopasdfghjklzxcvbnm')

a 1
b 1
c 1


# Cartesian product


In [ ]:
list1 = list(input().split())
list2 = list(input().split())
print(list1)
print(list2)

1 2
3 4
['1', '2']
['3', '4']


In [ ]:
for i in list1:
  for j in list2:
    print(f'({i}, {j})', end=' ')

(1, 3) (1, 4) (2, 3) (2, 4) 

# The Minion Game

In [ ]:
s = input()

vowels = 'AEIOU'

kevsc = 0
stusc = 0
for i in range(len(s)):
    if s[i].lower() in vowels.lower():
        kevsc += (len(s)-i)
    else:
        stusc += (len(s)-i)

if kevsc > stusc:
    print(f'Kevin wins {kevsc}')
elif kevsc < stusc:
    print(f'Stuart wins {stusc}')
else:
    print('Draw')

banana
Stuart wins 12


In [ ]:
string = 'BANANA'

In [ ]:
for i in range(len(string)):
  if string[i] in vowels:
    print(f'Vowels: {len(string) - i}')
  else:
    print(f'Consonants: {len(string) - i}')

Consonants: 6
Vowels: 5
Consonants: 4
Vowels: 3
Consonants: 2
Vowels: 1


In [ ]:
vowels

'AEIOU'

# Sets

In [ ]:
tot_sets = int(input())

for i in range(tot_sets):
  len_setA = int(input())
  setA = list(input().split())
  len_setB = int(input())
  setB = list(input().split())
  print(isSubset(setA, setB))

#for i in range(tot_sets):
 # print(IsSubset(list_setA[i], list_setB[i]))

3
5
1 2 3 4 5
9
9 8 5 6 3 2 1 4 7
True
1
2
5
3 6 5 4 14
False
7
1 2 3 5 6 8 9
3
9 8 2
False


In [ ]:
def isSubset(setA, setB):
  isSubset = False
  for i in range(len(setA)):
    if setA[i] in setB:
      isSubset = True
    else:
      isSubset = False
      break
  return isSubset

In [ ]:
setA = list(input().split())
tot_checkSet = int(input())
isSuperSet = False
for i in range(tot_checkSet):
  checkSet = list(input().split())
  if(isSubset(checkSet, setA)):
    isSuperSet = True
  else:
    isSuperSet = False
    break
print(isSuperSet)


1 2 3 4 5 6 7 8 9 10 11 12 23 45 84 78
2
1 2 3 4 5
100 11 12
False


In [ ]:
True and False

False

# Math

In [ ]:
import cmath

In [ ]:
cmath.phase(complex(1,2))

1.1071487177940904

In [ ]:
abs(complex(1,2))

2.23606797749979

In [ ]:
abs(complex(1 + 2j))

2.23606797749979

In [ ]:
str(round(math.degrees(math.atan2(10,20)))) + '°'

'27°'

In [ ]:
x, y = map(int, input().split())
val = eval(input())
print(val == y)

1 3
x**3 + x**2 + x + 1
False


In [ ]:
eval(input())

print(2+10)
12


In [ ]:
a, myList = int(input()), input().split()
print(all([int(i) > 0 for i in myList]) and any([j == j[::-1] for j in myList]))

6
1 2 3 4 5 -9
False


In [ ]:
all([5 > 4 and 2==2])

True

In [ ]:
print(zip([1, 2, 3, 4], 'hack'))

# Numpy

In [1]:
import numpy as np

In [ ]:
shape = list(map(int, input().split()))
print(np.zeros(shape, dtype=np.int))
print(np.ones(shape, dtype = np.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Depreca

In [ ]:
print(np.zeros([3, 3, 3]))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [9]:
myList = []
r, c = tuple(map(int, input().split()))
for i in range(r):
  myList.append(list(map(int, input().split())))
print(np.transpose(np.array(myList)))
print(np.array(myList).flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [14]:
list1 = []
list2 = []
n, m, p = tuple(map(int, input().split()))
for i in range(n):
  list1.append(list(map(int, input().split())))
for i in range(m):
  list2.append(list(map(int, input().split())))
np_array1 = np.array(list1, dtype = int)
np_array2 = np.array(list2, dtype = int)
print(np.concatenate(np.array(list1), np.array(list2)))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4


In [26]:
print(np.concatenate((np_array1, np_array2), axis = 0))

[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [36]:
print(np.eye(3, 3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
n, m = tuple(map(int, input().split()))
print(np.eye(n, m))

3 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [45]:
np_array = list({1, 3, 5, 2, 2})

In [48]:
np_array

[1, 2, 3, 5]

In [46]:
np_array[:2]

[1, 2]

In [47]:
np_array[2:]

[3, 5]

In [50]:
for i in range(2,5):
  print(i)

2
3
4


In [53]:
def checkSum(A, index):
  leftSum = 0
  rightSum = 0
  for j in range(index):
      leftSum += A[j]

  for k in range(index+1, len(A)):
      rightSum += A[k]

  return leftSum == rightSum
    
    
    #Function to find equilibrium point in the array.
def equalSum(A, N):
  # Your code here
  index = 0
  for i in range(len(A)):
      if(checkSum(A, i)):
          index = i+1
          break
  print(index)

In [54]:
equalSum([1,3,5,2,2], 5 )

3


In [55]:
equalSum(list(map(int, '4 42 27 16 28 3 4 5 9 3 31 5 5 29 10 18 35 35 33 19 41 23 8 32 9 5 8 18 35 13 6 7 6 10 11 13 37 2 25 7 28 43'.split())), 42)

0
